### ISSUE TITLE
Is this code working?

### ISSUE THREAD

**Issue by ronir121** [GSORF/Visual-GPS-SLAM#1]
Hi
I'm interested in your work on adding GPS measurements to DSO.
Is your code working properly? I saw many "todo" comments, and was wondering if the code is properly using GPs measurements now.
Thanx!

**Comment by GSORF** [comment]
Hi @ronir121,

Thank you for your question and interest.
Basically yes, but there are some issues which are discussed in the actual thesis report. It will be published here in great detail during the next two months. There are certain challenges with the DSO which make it hard to do it properly. Everything will be presented by example and evaluations of various situations and scenarios will be also be included.

I really hate to say this, but I would kindly ask you to please wait for the final publication of the thesis in about 1-2 months, I cannot really go into much detail for now, because this is still in WIP status for now. I hope you can understand this.

Kind regards,
Adam

**Comment by DamonMIN** [comment]
Waiting for your next publication.

**Comment by GSORF** [comment]
**Update:**
As of past friday (21.09.2018), a conference paper based on this thesis was accepted. Unfortunately, this means that publishing of the thesis is required to wait even longer as this would otherwise violate the conference rules. However, it is very fortunate that this research can soon be supported with an additional conference paper!

I still want to present improvements one could do to this code in short:
- GPS Measurements are read via UDP. This can work in certain situations, but may lead to a random order of measurements, which lead to wrong estimates in the Kalman Filter
- Synchronization of Video and GPS is crucial. Solving this issue only using software is hard.
- Conversion of GPS from Geodetic to Cartesian Coordinates using ECEF (Earth-Centered-Earth-Fixed) is not a good choice due to the curvature of trajectories along the earth's surface. Using UTM (Universal Traverse Mercator) may be better suited for the case of fusion with Visual SLAM
- The implementation does not estimate the global scale and orientation
- Integration of the filtered result back into the optimization loop in the DSO was hard to find without any info of their authors. At the end of the master thesis some potential parts in the code have been discovered, but this needs further investigation.

So, I want to be honest that there is still a lot of work to do (hence the WIP-comments in the code, where this mainly means that I tried stuff that just did't work - one can say that the DSO is very sensitive to changes made by someone who doesn't know the code very good. It also crashed a lot during my tests and therefore a fusion with GPS is still highly recommended.

Even though it might take more time, I will still publish my thesis and any papers related to that as soon as possible. Please excuse me that I am not able to do so directly after I wrote it.

Kind regards,
Adam

**Comment by GSORF** [comment]
Hello @DamonMIN and @ronir121,

the research papers are now publicly available:

1. VISAPP 2019: "B-SLAM-SIM: A novel approach to evaluate the fusion of Visual SLAM and GPS by example of Direct Sparse Odometry and Blender" by Adam Kalisz, Florian Particke, Dominik Penk, Markus Hiller and Jörn Thielecke. Link (VISAPP technical program): http://insticc.org/node/TechnicalProgram/visigrapp/presentationDetails/73753

2. DICTA 2018: "Systematic Analysis of Direct Sparse Odometry" by Florian Particke, Adam Kalisz, Christian Hofmann, Markus Hiller, Henrik Bey and Jörn Thielecke. Link (IEEEXPLORE): https://ieeexplore.ieee.org/document/8615807

Furthermore, I can also publish my thesis document now as well:
http://master.kalisz.co/MasterThesis_AdamKalisz_Online.pdf (120 MB)

Hope it is helpful for you. Feel free to contact me if you have any questions. I will close this issue now.

**Comment by ronir121** [comment]
Congratulations!
I'm now going over your publications, looks interesting.
Have you update the cpp code on github as well?

**Comment by GSORF** [comment]
Hi @ronir121,

Thank you. The code is in its final state for now. The main problem is how to do tight coupling within the DSO. It turned out that this was not possible for me yet, therefore I did investigate an uncoupled version, i.e. in my approach I can exchange the used Visual SLAM algorithm. Otherwise a full understanding of the code base is required (DSO has about 20,000 lines of code). I would like to change it in the future, but I have the feeling that it would be more goal orientated to write a custom Visual SLAM and do sensor data fusion based on code that was written by myself.

What is your opinion on that, do you agree that this makes sense?

Kind regards,
Adam
